const $ = (s) => document.querySelector(s);
const el = {
  refresh: $('#refresh-button'), notice: $('#notice'), connectionDot: $('#connection-dot'), connectionText: $('#connection-text'), identityText: $('#identity-text'), reelReadiness: $('#reel-readiness'), photoReadiness: $('#photo-readiness'), composerReadiness: $('#composer-readiness'), postKind: $('#post-kind'), accountSelect: $('#account-select'), accountHelp: $('#account-help'), mediaInput: $('#media-input'), mediaHelp: $('#media-help'), caption: $('#caption-input'), queueToggle: $('#queue-toggle'), scheduleInput: $('#schedule-input'), scheduleHelp: $('#schedule-help'), submit: $('#submit-button'), queueCount: $('#queue-count'), queueList: $('#queue-list'), queueRefresh: $('#queue-refresh-button'), managedAccountCount: $('#managed-account-count'), managedAccountList: $('#managed-account-list'), newAccount: $('#new-account-button'), prefillIdentity: $('#prefill-identity-button'), accountForm: $('#account-form'), accountId: $('#account-id-input'), accountName: $('#account-name-input'), accountFacebookId: $('#account-facebook-id-input'), accountExtension: $('#account-extension-select'), accountNotes: $('#account-notes-input'), accountEnabled: $('#account-enabled-input'), accountCancel: $('#account-cancel-button'), accountSave: $('#account-save-button'), tabs: [...document.querySelectorAll('.tab-button')], panels: [...document.querySelectorAll('.workspace-panel')],
};
const state = { baseUrl: 'https://fb.shopcongngheso5.io.vn', extensionId: null, health: null, accounts: [], extensions: [], submitting: false };
const kind = () => el.postKind.value || 'post_reel';
const url = (path, query = {}) => { const u = new URL(path, `${state.baseUrl}/`); Object.entries(query).forEach(([k, v]) => { if (v != null && v !== '') u.searchParams.set(k, v); }); return u; };
async function api(path, options = {}, query = {}) { const headers = new Headers(options.headers || {}); if (options.body && !(options.body instanceof FormData) && !headers.has('Content-Type')) headers.set('Content-Type', 'application/json'); const r = await fetch(url(path, query), { ...options, headers }); const text = await r.text(); let data; try { data = text ? JSON.parse(text) : {}; } catch (_) { data = { detail: text }; } if (!r.ok) throw new Error(data.detail || data.error || `HTTP ${r.status}`); return data; }
function notice(message = '', type = 'info') { el.notice.hidden = !message; el.notice.className = `notice is-${type}`; el.notice.textContent = message; }
function badge(node, label, ok) { node.textContent = `${label}: ${ok ? 'sẵn sàng' : 'cần capture tay'}`; node.className = `badge ${ok ? 'is-ok' : 'is-warn'}`; }
function matching(a) { return !state.extensionId || !a.extension_id || a.extension_id === state.extensionId; }
function connected() { return Boolean(state.health?.extension_connected); }
function ready() { return kind() === 'post_reel' ? Boolean(state.health?.has_template) : Boolean(state.health?.has_photo_template); }
function action(label, cls, fn) { const b = document.createElement('button'); b.type = 'button'; b.className = `queue-action ${cls}`; b.textContent = label; b.onclick = fn; return b; }
function renderHealth(h, identity) { state.health = h; const ok = Boolean(h?.extension_connected); el.connectionDot.className = `status-dot ${ok ? 'is-ok' : 'is-error'}`; el.connectionText.textContent = ok ? 'Extension đã kết nối bridge' : 'Extension chưa kết nối bridge'; badge(el.reelReadiness, 'Reel', Boolean(h?.has_template)); badge(el.photoReadiness, 'Ảnh', Boolean(h?.has_photo_template)); badge(el.composerReadiness, kind() === 'post_reel' ? 'Reel' : 'Ảnh', ready()); const id = identity?.id || h?.fb_user?.id, name = identity?.name || h?.fb_user?.name; el.identityText.textContent = id ? `Đang hoạt động: ${name || `Fanpage ${id}`} (${id})` : 'Chưa xác định Fanpage đang hoạt động. Hãy mở một tab facebook.com đã đăng nhập.'; }
function renderExtensionOptions(selected = state.extensionId) { el.accountExtension.replaceChildren(); const items = [...state.extensions]; if (state.extensionId && !items.some(x => x.id === state.extensionId)) items.unshift({ id: state.extensionId, connected: false }); if (!items.length) el.accountExtension.add(new Option('Extension hiện tại', state.extensionId || '')); else items.forEach(x => el.accountExtension.add(new Option(`${x.id} · ${x.connected ? 'đang kết nối' : 'không kết nối'}`, x.id))); el.accountExtension.value = selected || state.extensionId || ''; }
function renderAccounts(accounts) { state.accounts = accounts; const previous = el.accountSelect.value, eligible = accounts.filter(a => a.enabled && matching(a)); el.accountSelect.replaceChildren(new Option(eligible.length ? 'Chọn Fanpage để đăng / xếp lịch' : 'Chưa có Fanpage đang bật', '')); eligible.forEach(a => el.accountSelect.add(new Option(`${a.name || 'Fanpage'} (${a.facebook_id || '—'})`, a.id))); el.accountSelect.value = eligible.some(a => a.id === previous) ? previous : ''; el.accountHelp.textContent = eligible.length ? 'Chọn Fanpage đang bật và thuộc extension hiện tại.' : 'Mở tab Fanpage để thêm hoặc bật Page.'; renderManagedAccounts(); }
function renderManagedAccounts() { const accounts = state.accounts.filter(matching); el.managedAccountCount.textContent = accounts.length; el.managedAccountList.replaceChildren(); if (!accounts.length) { el.managedAccountList.innerHTML = '<p class="empty-state">Chưa có Fanpage. Bấm “Thêm Page” để bắt đầu.</p>'; return; } accounts.forEach(a => { const item = document.createElement('article'); item.className = `managed-account${a.enabled ? '' : ' is-disabled'}`; item.innerHTML = `<div class="managed-account-title"><span>${a.name || 'Fanpage'}</span><span>${a.enabled ? 'Đang bật' : 'Đã tắt'}</span></div><p class="managed-account-meta">ID: ${a.facebook_id || '—'} · Extension: ${a.extension_id || 'chưa gán'}${a.notes ? ` · ${a.notes}` : ''}</p>`; const actions = document.createElement('div'); actions.className = 'account-actions'; actions.append(action('Sửa', '', () => openAccount(a)), action(a.enabled ? 'Tắt Page' : 'Bật Page', '', () => toggleAccount(a)), action('Xóa', 'danger', () => deleteAccount(a))); item.append(actions); el.managedAccountList.append(item); }); }
function formatTime(s) { return s ? new Date(Number(s) * 1000).toLocaleString('vi-VN') : 'chạy ngay'; }
function renderQueue(jobs) { el.queueCount.textContent = jobs.length || ''; el.queueList.replaceChildren(); if (!jobs.length) { el.queueList.innerHTML = '<p class="empty-state">Chưa có bài trong hàng đợi.</p>'; return; } jobs.slice(0, 25).forEach(j => { const item = document.createElement('article'); item.className = 'queue-item'; const input = j.input || {}; item.innerHTML = `<div class="queue-title"><span>${j.kind === 'post_photos' ? 'Ảnh / Album' : 'Reel'}</span><span>${j.status || 'unknown'}</span></div><p class="queue-meta">${input.caption || 'Không có nội dung'} · ${formatTime(j.run_at || j.runAt)}${j.error ? ` · Lỗi: ${j.error}` : ''}</p>`; if (['queued', 'failed', 'canceled', 'cancelled'].includes(j.status)) { const actions = document.createElement('div'); actions.className = 'queue-actions'; if (j.status === 'queued') actions.append(action('Hủy', 'danger', () => job(j.id, 'cancel'))); if (['failed', 'canceled', 'cancelled'].includes(j.status)) actions.append(action('Thử lại', '', () => job(j.id, 'retry'))); item.append(actions); } el.queueList.append(item); }); }
async function config() { const saved = await chrome.storage.local.get(['serverUrl', 'extensionId']); state.baseUrl = String(saved.serverUrl || state.baseUrl).replace(/\/+$/, ''); state.extensionId = saved.extensionId || null; try { const live = await chrome.runtime.sendMessage({ type: 'get_popup_status' }); if (live?.serverUrl) state.baseUrl = live.serverUrl; if (live?.extensionId) state.extensionId = live.extensionId; return live; } catch (_) { return null; } }
async function refresh() { el.refresh.disabled = true; try { const live = await config(); const health = await api('/api/health', {}, { extension_id: state.extensionId }); if (live?.connected) health.extension_connected = true; let identity = null; if (state.extensionId && health.extension_connected) try { identity = await api(`/api/extensions/${encodeURIComponent(state.extensionId)}/identity`); } catch (_) {} const [ar, jr, er] = await Promise.all([api('/api/accounts'), api('/api/jobs', {}, { limit: 40 }), api('/api/extensions')]); state.extensions = Array.isArray(er.items) ? er.items : []; renderHealth(health, identity); renderExtensionOptions(el.accountExtension.value || state.extensionId); renderAccounts(Array.isArray(ar.items) ? ar.items : []); renderQueue(Array.isArray(jr.items) ? jr.items : []); if (!health.extension_connected) notice('Bridge chưa nhận extension trên server. Kiểm tra URL server và bridge.', 'error'); else if (!ready()) notice('Loại bài này chưa có mẫu capture. Hãy đăng tay một bài cùng loại trước.', 'info'); else notice(); } catch (e) { renderHealth(null, null); renderAccounts([]); renderQueue([]); notice(`Không thể kết nối server FBEM (${state.baseUrl}): ${e.message}`, 'error'); } finally { el.refresh.disabled = false; } }
async function job(id, op) { try { await api(`/api/jobs/${encodeURIComponent(id)}/${op}`, { method: 'POST', body: '{}' }); notice(op === 'cancel' ? 'Đã hủy tác vụ.' : 'Đã đưa tác vụ vào hàng đợi lại.', 'success'); refresh(); } catch (e) { notice(`Không thể cập nhật tác vụ: ${e.message}`, 'error'); } }
function openAccount(a = null) { el.accountForm.hidden = false; el.accountId.value = a?.id || ''; el.accountName.value = a?.name || ''; el.accountFacebookId.value = a?.facebook_id || ''; el.accountNotes.value = a?.notes || ''; el.accountEnabled.checked = a ? Boolean(a.enabled) : true; renderExtensionOptions(a?.extension_id || state.extensionId); el.accountSave.textContent = a ? 'Cập nhật Fanpage' : 'Lưu Fanpage'; el.accountName.focus(); }
function closeAccount() { el.accountForm.reset(); el.accountId.value = ''; el.accountForm.hidden = true; }
function payload() { return { name: el.accountName.value.trim(), facebookId: el.accountFacebookId.value.trim(), extensionId: el.accountExtension.value || state.extensionId || '', accountType: 'page', notes: el.accountNotes.value.trim(), enabled: el.accountEnabled.checked }; }
async function saveAccount(e) { e.preventDefault(); const p = payload(), id = el.accountId.value; if (!p.name || !p.facebookId) return notice('Hãy nhập tên và Facebook Page ID.', 'error'); try { await api(id ? `/api/accounts/${encodeURIComponent(id)}` : '/api/accounts', { method: id ? 'PUT' : 'POST', body: JSON.stringify(p) }); closeAccount(); notice(id ? 'Đã cập nhật Fanpage.' : 'Đã thêm Fanpage.', 'success'); refresh(); } catch (e) { notice(`Không thể lưu Fanpage: ${e.message}`, 'error'); } }
async function toggleAccount(a) { try { await api(`/api/accounts/${a.id}`, { method: 'PUT', body: JSON.stringify({ ...a, facebookId: a.facebook_id, extensionId: a.extension_id, accountType: a.account_type, enabled: !a.enabled }) }); refresh(); } catch (e) { notice(`Không thể cập nhật Fanpage: ${e.message}`, 'error'); } }
async function deleteAccount(a) { if (!confirm(`Xóa Fanpage “${a.name || a.facebook_id}”?`)) return; try { await api(`/api/accounts/${a.id}`, { method: 'DELETE' }); notice('Đã xóa Fanpage.', 'success'); refresh(); } catch (e) { notice(`Không thể xóa Fanpage: ${e.message}`, 'error'); } }
async function prefill() { const id = el.accountExtension.value || state.extensionId; try { const identity = await api(`/api/extensions/${encodeURIComponent(id)}/identity`); if (!identity?.id) throw new Error('Không tìm thấy Page hiện tại. Hãy mở Facebook và chuyển sang Page cần dùng.'); openAccount(); el.accountExtension.value = id; el.accountFacebookId.value = identity.id; el.accountName.value = identity.name || `Fanpage ${identity.id}`; notice('Đã điền Page đang hoạt động. Kiểm tra rồi bấm Lưu Fanpage.', 'success'); } catch (e) { notice(`Không thể lấy Page đang hoạt động: ${e.message}`, 'error'); } }
function updateComposer() { const photo = kind() === 'post_photos'; el.mediaInput.accept = photo ? 'image/jpeg,image/png' : 'video/mp4,video/quicktime'; el.mediaInput.multiple = photo; el.mediaHelp.textContent = photo ? 'Chọn một hoặc nhiều ảnh .jpg, .jpeg hoặc .png.' : 'Chọn đúng một video .mp4 hoặc .mov.'; el.scheduleInput.disabled = !el.queueToggle.checked; el.submit.textContent = el.queueToggle.checked ? 'Tạo lịch trong hàng đợi' : 'Đăng ngay'; el.scheduleHelp.textContent = el.queueToggle.checked ? 'Chọn thời điểm chạy trong hàng đợi.' : 'Đăng trực tiếp sau khi upload media.'; if (state.health) badge(el.composerReadiness, photo ? 'Ảnh' : 'Reel', ready()); }
function validate(files) { if (!files.length) throw new Error('Hãy chọn tệp media.'); const names = [...files].map(f => f.name.toLowerCase()); if (kind() === 'post_reel' && (files.length !== 1 || !names.every(n => /\.(mp4|mov)$/.test(n)))) throw new Error('Reel yêu cầu đúng một tệp .mp4 hoặc .mov.'); if (kind() === 'post_photos' && !names.every(n => /\.(jpe?g|png)$/.test(n))) throw new Error('Ảnh/Album chỉ hỗ trợ .jpg, .jpeg hoặc .png.'); }
async function stage(files) { const out = []; for (const f of files) { const form = new FormData(); form.set('file', f, f.name); out.push(await api('/api/media/upload', { method: 'POST', body: form })); } return out; }
async function post() { if (state.submitting) return; try { if (!connected()) throw new Error('Extension chưa kết nối bridge.'); if (!ready()) throw new Error('Chưa có mẫu capture cho loại bài này.'); const account = state.accounts.find(a => a.id === el.accountSelect.value); if (!account) throw new Error('Hãy chọn Fanpage đang bật.'); validate(el.mediaInput.files); let runAt; if (el.queueToggle.checked) { runAt = Math.floor(new Date(el.scheduleInput.value).getTime() / 1000); if (!runAt || runAt <= Date.now() / 1000) throw new Error('Chọn thời điểm ở tương lai.'); } state.submitting = true; el.submit.disabled = true; notice('Đang tải media vào FBEM…', 'info'); const files = await stage(el.mediaInput.files); const input = kind() === 'post_reel' ? { videoUrl: files[0].url, caption: el.caption.value } : { imageUrls: files.map(x => x.url), caption: el.caption.value }; if (el.queueToggle.checked) await api('/api/jobs', { method: 'POST', body: JSON.stringify({ accountId: account.id, extensionId: account.extension_id || state.extensionId, kind: kind(), input, runAt, idempotencyKey: `sidepanel-${Date.now()}-${crypto.randomUUID()}` }) }); else await api(kind() === 'post_reel' ? '/post-reel' : '/post-photos', { method: 'POST', body: JSON.stringify({ ...input, pageId: account.facebook_id, extensionId: account.extension_id || state.extensionId }) }); notice(el.queueToggle.checked ? 'Đã tạo lịch trong hàng đợi.' : 'Đăng bài thành công.', 'success'); el.mediaInput.value = ''; el.caption.value = ''; refresh(); } catch (e) { notice(`Không thể xử lý bài đăng: ${e.message}`, 'error'); } finally { state.submitting = false; el.submit.disabled = false; } }
function tab(button) { el.tabs.forEach(b => { const active = b === button; b.classList.toggle('is-active', active); b.setAttribute('aria-selected', active); }); el.panels.forEach(p => { const active = p.id === button.dataset.panel; p.hidden = !active; p.classList.toggle('is-active', active); }); }
el.tabs.forEach(b => b.onclick = () => tab(b)); el.refresh.onclick = refresh; el.queueRefresh.onclick = refresh; el.postKind.onchange = updateComposer; el.queueToggle.onchange = updateComposer; el.submit.onclick = post; el.newAccount.onclick = () => openAccount(); el.prefillIdentity.onclick = prefill; el.accountCancel.onclick = closeAccount; el.accountForm.onsubmit = saveAccount; renderExtensionOptions(); updateComposer(); refresh();
