"""Standalone WebSocket server on :9224 for the Chrome extension bridge.

Kept separate from the FastAPI :47102 app to match flowgen's pattern — the
extension's `background.js` connects to `ws://127.0.0.1:9224` only.
"""
from __future__ import annotations

import asyncio
import json
import logging

import websockets

from .config import EXTENSION_WS_PORT, WS_HOST
from .connection_registry import connection_registry
from .bridge_client import bridge_client

logger = logging.getLogger(__name__)


async def _handler(websocket) -> None:
    # The first frame is a stable hello generated by the extension installation.
    # Older extensions are accepted under a legacy id for backwards compatibility.
    extension_id = "legacy"
    try:
        raw_hello = await asyncio.wait_for(websocket.recv(), timeout=5)
        hello = json.loads(raw_hello)
        if hello.get("type") == "hello" and hello.get("extensionId"):
            extension_id = str(hello["extensionId"])
        else:
            # Preserve the first non-hello telemetry frame.
            connection_registry.register(extension_id, websocket)
            connection_registry.handle_message(extension_id, hello)
    except Exception:  # noqa: BLE001
        logger.warning("extension did not send a valid hello; using legacy id")

    session = connection_registry.get(extension_id) or connection_registry.register(extension_id, websocket)
    # Legacy MCP/HTTP endpoints continue to target the most recently connected
    # extension. Dashboard jobs always use the explicit registry session.
    bridge_client.set_extension(websocket)
    logger.info("extension %s connected from %s", extension_id, getattr(websocket, "remote_address", "?"))

    # Hand the extension the secret it needs to authenticate HTTP callbacks.
    try:
        await websocket.send(
            json.dumps({"type": "callback_secret", "secret": session.callback_secret, "extensionId": extension_id})
        )
    except Exception:  # noqa: BLE001
        logger.exception("failed to send callback_secret")

    try:
        async for raw in websocket:
            try:
                data = json.loads(raw)
            except json.JSONDecodeError:
                logger.warning("invalid JSON from extension")
                continue
            try:
                connection_registry.handle_message(extension_id, data)
                await bridge_client.handle_message(data)
            except Exception:  # noqa: BLE001
                logger.exception("error handling extension message")
    except websockets.ConnectionClosed:
        pass
    finally:
        connection_registry.unregister(extension_id, websocket)
        bridge_client.clear_extension(websocket)
        logger.info("extension %s disconnected", extension_id)


async def run_ws_server() -> None:
    async with websockets.serve(_handler, WS_HOST, EXTENSION_WS_PORT):
        logger.info("WebSocket server listening on ws://%s:%d", WS_HOST, EXTENSION_WS_PORT)
        await asyncio.Future()  # run forever
